# Generated by Django 3.1.1 on 2021-04-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wspomaganie_decyzji', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeria',
            name='przestrzen_gastronomiczna',
            field=models.CharField(choices=[('1', 'Dobrze'), ('2', 'Dobrze+'), ('3', 'Dobrze++'), ('4', 'Źle'), ('5', 'Źle-'), ('6', 'Źle--')], max_length=50),
        ),
    ]
