# Generated by Django 3.1.1 on 2021-04-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wspomaganie_decyzji', '0003_galeria_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeria',
            name='image',
            field=models.ImageField(blank=True, default='building.png', null=True, upload_to='wspomaganie_decyzji/'),
        ),
    ]
