# Generated by Django 3.1.1 on 2021-04-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wspomaganie_decyzji', '0005_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galeria',
            old_name='przestrzen_gastronomiczna',
            new_name='artykuły_spożywcze',
        ),
        migrations.RenameField(
            model_name='galeria',
            old_name='wiek_obiektu',
            new_name='rozrywka',
        ),
        migrations.RenameField(
            model_name='galeria',
            old_name='strefa_wizualna',
            new_name='wyglad_obiektu',
        ),
        migrations.RemoveField(
            model_name='galeria',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='galeria',
            name='bankomat',
        ),
        migrations.RemoveField(
            model_name='galeria',
            name='fryzjer',
        ),
        migrations.RemoveField(
            model_name='galeria',
            name='kino',
        ),
        migrations.RemoveField(
            model_name='galeria',
            name='kregielnia',
        ),
        migrations.RemoveField(
            model_name='galeria',
            name='obecnosc_hipermarketu',
        ),
        migrations.RemoveField(
            model_name='galeria',
            name='operator_komorkowy',
        ),
        migrations.RemoveField(
            model_name='galeria',
            name='strefa_dla_dzieci',
        ),
        migrations.AddField(
            model_name='galeria',
            name='uslugi',
            field=models.CharField(choices=[('1', 'Bardzo Stary'), ('2', 'Stary+'), ('3', 'Średni'), ('4', 'Nowy'), ('5', 'Dopiero zbudowany (>rok)')], default=2, max_length=50),
            preserve_default=False,
        ),
    ]
