# Generated by Django 3.1.1 on 2021-04-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wspomaganie_decyzji', '0006_auto_20210428_1019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galeria',
            old_name='artykuły_spożywcze',
            new_name='artykuly_spozywcze',
        ),
        migrations.AlterField(
            model_name='galeria',
            name='rozrywka',
            field=models.CharField(choices=[('1', 'Bardzo niski poziom'), ('2', 'Niski poziom'), ('3', 'Średni poziom'), ('4', 'Wysoki poziom'), ('5', 'Bardzo wysoki poziom')], max_length=50),
        ),
        migrations.AlterField(
            model_name='galeria',
            name='uslugi',
            field=models.CharField(choices=[('1', 'Bardzo niski poziom'), ('2', 'Niski poziom'), ('3', 'Średni poziom'), ('4', 'Wysoki poziom'), ('5', 'Bardzo wysoki poziom')], max_length=50),
        ),
    ]
