# Generated by Django 3.1.1 on 2021-05-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wspomaganie_decyzji', '0007_auto_20210428_1034'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.AlterField(
            model_name='galeria',
            name='artykuly_spozywcze',
            field=models.CharField(choices=[('1', 'Źle--'), ('2', 'Źle-'), ('3', 'Źle'), ('4', 'Dobrze'), ('5', 'Dobrze+'), ('6', 'Dobrze++')], max_length=50),
        ),
        migrations.AlterField(
            model_name='galeria',
            name='wyglad_obiektu',
            field=models.CharField(choices=[('1', 'Źle--'), ('2', 'Źle-'), ('3', 'Źle'), ('4', 'Dobrze'), ('5', 'Dobrze+'), ('6', 'Dobrze++')], max_length=50),
        ),
    ]
